volumes:
  rabbitmq_data:
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
      - "1883:1883"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  perf_tool:
    image: pivotalrabbitmq/perf-test
    container_name: perf_tool
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: >
      ./runjava.sh com.rabbitmq.perf.PerfTest
      --uri amqp://mqadmin:mq4dm1n_pass@rabbitmq:5672 
      --producers ${PRODUCERS}
      --consumers ${CONSUMERS}
      --queue ${QUEUE}
      --id ${ID}
      --time ${TIME}
      --size ${SIZE}
      ${EXTRA_ARGS}
networks:
  default:
    driver: bridge
